### ISSUE TITLE
standards with wrong formula

### ISSUE THREAD

**Issue by jorainer** [EuracBiomedicalResearch/lcms-standards#12]
Checking manually all information for the standards from HMDB, for one standard the formula differs:

- propionic acid (HMDB0000237): formula old: CH3CH2CO2H, formula from HMDB: C3H6O2

**Comment by jorainer** [comment]
@mar-garcia, can you please check the ions for this one?

**Comment by mar-garcia** [comment]
I think that both formulas are the same, but written in a different way... I mean, both CH3CH2CO2H & C3H6O2 are associated to a neutral mass of 74.03677

**Comment by jorainer** [comment]
well, that makes it easier. so we skip that one.

**Comment by jorainer** [comment]
I think we can close this issue now since you've updated the table.
