### ISSUE TITLE
standards with wrong neutral mass

### ISSUE THREAD

**Issue by jorainer** [EuracBiomedicalResearch/lcms-standards#13]
Compounds for which the provided neutral mass differs by more than 0.1 from the neutral mass listed in HMDB:

- NADP (HMDB0000217) mass old: 743.0755; formula correct C21H29N7O17P3, mass 744.0833
- Sphingosine-1-phosphate (HMDB0000277) mass old: 379.4718; formula correct C18H38NO5P, mass 379.2488
- Thiamine (HMDB0000235) mass old: 264.1045; formula correct C12H17N4OS, mass 265.1123
- Phosphorylcholine (HMDB0001565) mass old: 183.0660; formula correct C5H15NO4P, mass 184.0739
- dUTP (HMDB0001191) mass old: 468.1417; formula correct C9H15N2O14P3, mass 467.9736
- NAD (HMDB0000902) mass old: 663.1091; formula correct C21H28N7O14P2, mass 664.1169

**Comment by jorainer** [comment]
@mar-garcia, can you please re-check the ions for these?

**Comment by mar-garcia** [comment]
- **Sphingosine-1-phosphate (MIX-06):** RT = 148, [M+H]+, [M-H]-
- **dUTP (MIX-13):** RT=195, but I cannot see any related ion in the spectra.
- **NADP (MIX-05):** looking at the spectra it seems that neural mass is 743.07543 (C21H28N7O17P3). Let's confirm the commercial number of the standard with @vveri   
- **Thiamine (MIX-12):** looking at the spectra it seems that neutral mass is 264.10447 (C12H16N4OS). Let's confirm the commercial code of the std with @vveri 
- **Phosphorylcholine (MIX-13):** looking at the spectra it seems that neutral mass is 183.06603 (C5H14NO4P). Let's confirm the commercial code of the std with @vveri 
- **NAD (MIX-14):** looking at the spectra it seems that neutral mass is 663.10910 (C21H27N7O14P2). Let's confirm the commercial code of the std with @vveri . In negative maybe the highest ion is a fragment with an mz value = 540.0535

**Comment by mar-garcia** [comment]
- **NADP (MIX-05):** Sigma-Aldrich - N5755 = β-Nicotinamide adenine dinucleotide phosphate hydrate C21H28N7O17P3 · xH2O --> I would keep the formula C21H28N7O17P3
- **Thiamine (MIX-12):** Sigma Aldrich – T4625 = Thiamine hydrochloride C12H17ClN4OS · HCl --> I would keep the formula C12H16N4OS (= C12H17ClN4OS - HCl)
- **Phosphorylcholine (MIX-13):** Sigma Aldrich – P0378 = Phosphocholine chloride calcium salt tetrahydrate CaO3POCH2CH2N(Cl)(CH3)3 · 4H2O --> C5H14NO4P (CaO3POCH2CH2N(Cl)(CH3)3 - CaCl + H)
- **NAD (MIX-14):** Sigma Ladrich – N1636 = β-Nicotinamide adenine dinucleotide hydrate C21H27N7O14P2 · xH2O --> I would keep the formula C21H27N7O14P2

**Comment by mar-garcia** [comment]
**Phosphorylcholine (MIX-13):** 
![phosphorylcholine_NEG_adductFA](https://user-images.githubusercontent.com/7772578/68218003-ecfa5a80-ffe3-11e9-989d-0b3a90ea1717.png)
![phosphorylcholine_POS](https://user-images.githubusercontent.com/7772578/68218005-ecfa5a80-ffe3-11e9-87a5-2a07ddfaeedc.png)

**Comment by jorainer** [comment]
Summarizing: seems that the neutral mass reported in HMDB is off by one *H* for most/all of these compounds. This was corrected by @mar-garcia , i.e. the formula in the *standards* txt file was adapted accordingly. Note however that the formula does now **no longer** match the formula reported in HMDB.
