### ISSUE TITLE
Create R-code to create EIC for all standards in serum samples

### ISSUE THREAD

**Issue by jorainer** [EuracBiomedicalResearch/lcms-standards#22]
Setup the R-code/Rmd file to create EIC images for all standards.

- Process all mzML files of the *new* standards experiment (2020-01) and create EICs for the standards added to these.
- The EIC images should contain:
  - EIC full retention time range for an ion for QC sample, water low concentration, water high concentration, serum low concentration, serum high concentration.
  - EIC zoomed into the region of the expected peak (using the rt previously defined on water samples) with the same samples as above.
  - EIC zoomed with only QC, serum low concentration, serum high concentration.

**Comment by mar-garcia** [comment]
Done in pull request #25
