### ISSUE TITLE
Specify retention times of standards observed in serum samples

### ISSUE THREAD

**Issue by jorainer** [EuracBiomedicalResearch/lcms-standards#23]
The goal is to update the retention times of the standards in the *standards_dilution.txt* file by looking through the EICs generated in issue #22.

Add also additional columns to the table:
- `"data_set"`: the name of the data set on which the rt was defined, e.g. `"2016 water"` or `"2020-standards-serum"`.
- `"sample"`: information on the sample in which the rt was measured (or in which the standard was dissolved). For example `"water"` or `"QC CHRIS"`.
- additional columns with `TRUE`/`FALSE` for specific peak/data characteristics seen in the EIC. For example `"single_peak"` to characterize compounds for which a single peak or multiple peaks were observed at the reported retention time, or `"stable_rt"` if the retention time for low and high concentration was the same. Ideally, the column should be named so that `TRUE` would mean good quality, `FALSE` not so good. That way it would be easier to calculate a final score for the rt.
- `"operator"`: the name of the person who defined the rt.

**Comment by mar-garcia** [comment]
Partly done in pull request #25 
It is still missing: add a column with the peak shape quality.

**Comment by mar-garcia** [comment]
Updated columns with peak shape quality
