### ISSUE TITLE
Peak detection problems

### ISSUE THREAD

**Issue by mar-garcia** [EuracBiomedicalResearch/lcms-standards#6]
**Internal Standards:**
_[To check with JR]_

- Most of compounds are not detected in sample 1 due to RT variations  
- Usually carnitine is splited in 2 different peaks (at least in POS). Changing _peakwidth()_ parameter does not solve it  
- Calibrations in POS: 20 ppm ; 3-4 mDa

**Comment by jorainer** [comment]
To select the *best* peak for an ion I would suggest the following:
- calculate the difference between `"rtmed"` and the expected retention time.
- subset the peak matrix to rows (peaks) for which this difference (the absolute value of the difference) is smaller than 60 seconds.
- among the subsetted peaks, choose the one with the highest intensity.
